---
resources:
- name: git-sandbox-bot-stage
  type: git
  source:
    uri: https://github.com/18f/cg-sandbox-bot
    branch: staging
- name: git-sandbox-bot-prod
  type: git
  source:
    uri: https://github.com/18f/cg-sandbox-bot
    branch: master

- name: deploy-bot-stage
  type: cf
  source:
    api: https://api.green.18f.gov
    username: {{cf-username-staging}}
    password: {{cf-password-staging}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
- name: deploy-bot-prod
  type: cf
  source:
    api: https://api.cloud.gov
    username: {{cf-username-production}}
    password: {{cf-password-production}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false


jobs:
- name: deploy-bots-stage
  serial: true
  plan:
  - aggregate:
    - get: git-sandbox-bot-stage
      trigger: true
  - aggregate:
    - put: deploy-bot-stage
      params:
        manifest: git-sandbox-bot-stage/manifest-staging.yml
        path: git-sandbox-bot-stage
        current_app_name: sandbox-bot-staging
        environment_variables:
          CLIENT_ID: {{client-id}}
          CLIENT_SECRET: {{client-secret-staging}}
          UAA_URL: {{uaa-url-staging}}
          SLACK_HOOK: {{slack-webhook-url}}
- name: deploy-bots-prod
  serial: true
  plan:
  - aggregate:
    - get: git-sandbox-bot-prod
      trigger: true
  - aggregate:
    - put: deploy-bot-prod
      params:
        manifest: git-sandbox-bot-prod/manifest.yml
        path: git-sandbox-bot-prod
        current_app_name: sandbox-bot
        environment_variables:
          CLIENT_ID: {{client-id}}
          CLIENT_SECRET: {{client-secret-production}}
          UAA_URL: {{uaa-url-prodution}}
          SLACK_HOOK: {{slack-webhook-url}}
